travis:
  secure:
    BINSTAR_TOKEN: DApuu+vxzDHLQpBLOnXJOQ5t7E0Bp1LRu6PCJaQzSK2gbof+KAp1lo4gKBJce6fIt8dIiVQARVH8lt/smJ0A8HE2TFzQ+mAvm1zol4FyactzQ+chGDnkOeGxPedHLWFVGTSAvg5suvF0YgeDwCV7oprjy/ikHxxkxqLRJkOjrgcChcCcmxAQ8bEcre0IfIEQJ6zucEtTb6PMARNaQQN9A/f7ORfEooHXynMEJy/+uarDoYH78nvZDMpX8Nz5CakNjs61L/Oco95h59bJl4VYqpnf4JxnDiNPdhPtY4+c1c2QlYhfzCyk7zsjzK0TUSqAFolJ8QCTyWOg6ViLJbvPKnouolE77rnT5rpDgDh7P3wANc5FNQxtnD+hyJFmD8/w2e9H6FYkCdXM1Nyix61nIECuqH/bEXlRltQC/mFrmerky/UjDrMCSbUQ52RzBMo12G9tqeylnOnuNZeHA1OJxmI0HoPQLFn4m704Xn3WxIUnp5QaMDsxl5uQMyVlTxagsY7d7ilRpPOm16zL01NClX0V9EKAU6qmK7BNClsIAUSJlVBp+m/ERLGr6S2qdO8tRVPTFmeXLG7J3kNKnchaIAcRg+VuGsHM98TdIG0eVaI+pUaf8QHDm/ZvgqlJyMu5vTzOat0rlzDD5cQywN3y/SijGiKCAaqRqRaSS0fKE40=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
