travis:
  secure:
    BINSTAR_TOKEN: G3zwPoKD05R92NK+f24p3H1LyEeXqfg2fpNfFswy9YwjESRJG550IsEScgtKr2GwjTcbwHYBttOppHHao8v+2CTzfCOBpSi2G37WgNr7O0RsVEG5O8U5puSUJqLUHzaYvSDLHxYkULMYcKMjiMX+8MgnANSNgRhXqaUFLyCueAe+6leOxTVyZLv9bXhoXYaQb7EcGnsGlRdZfKlL6T3OtsAKjrCZR2qPdpiO9+Kq7FaRCNBP11GUHrs3D/a6dZ7gyUVw+QAwy8DgiXh+rEVwpvqacDoHHbwh7QYXuWR5WCHy4v5jZah2OCKG47UrKtGcljiEo67V2NtguOD47goGnvRZCEamNhFGXXsk+A5GpNjI2lLy08Kokhs1RWj58UdLSM3QslUH8FQ3RmyNUBPrX3rw4CNjARLHdFXrCUZvm5lHSYGhwqRaEpYyrj7dzyzdDjSU4mAuSsNJoLX13EIxQXfEuCYcw9ie5/z6V1WZv3/gZfc/Q3bp/l6a8ZhR+aKFXX6gl3Ptxjqn5HYkMSHlZEZk8H7D0Fxa+Z3e6e/ilLQKfJ9kXTcMzz/2V92NdszgK42qCzZwpDqQDQfrfRTmT5MKL7Amki5ych8CZxQ6+QziIkiLN9pPxBQhPWcqBfSNsJ8MtwP3RiOrMneTHacTAmVuE9GmtJ2S9WeHk1MZRfk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
