travis:
  secure:
    BINSTAR_TOKEN: ar74Cf/YWMWDhB9qdGc07xR0ycIVZ+xnbvNxx+1fEX9mzm49vbxvmejBkN+lpvmJb3FqPy8yNNyF3crYqzhe3VrNVFJQCVeMQFsoPlJi3zA6wbPiWg7jz6TUwT3Xxj5KOs+wP9//uBJ735O310Ov9ACK35IiRY77a8vfQqM+A8PbGQeINFc03tpv15kFravV2v/cuevasMp91LrznNOhtPnJZy+LABKiYJsmJOs8dNTV/PFwOjBWaMFSB6suv/PLwbMafCG8rHAxvnHclQoQCrDxqieITRM2jWLnBdTYZIbdfuXcxB214GulzOuTlUcYHDwkUixX4/gBb6NGcL7BrMXFxFu8EgIwPOXpr1k3SS9iAZ1c7O7Hmfny63gQEtCnxKaC9l0vPAcZ+g9FpHO3ZDOOp72IMirkzVsEN36NCweXWbwc/MS0kJxECSKFCs7pikYpVeJBT2sMtrgpbNR6mKf3QrCa1z5nbwf5Un7hdNEIcFo/Mp0HJARsy8NZJzzKL4ZrPn/aOy/r1da+cufa8sXJQqbh8j31IoHaJCxD6/hzuhaFnWuKATc2kvaMndMHIuKXXEIsynEZJ2KugKmr8H6TKdkQ/7zwi2vPgYscwEVi+ZF3bUZ59WItsR468C4VdjhIhG/rxyEP4GKi4Z3IL9WCe1cKoclQg3zS5VTKEzY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
